version: "3"

services:
  convert:
    container_name: convert
    image: xhmm/tfjs-converter:with-mirror
    build:
      context: .
    environment:
      - test=hi
    env_file:
      - .env
    volumes:
      - ./models:${in}
      - ./converted:${out}
